name: Deploy to Org
on:
  workflow_dispatch:
    inputs:
      org:
        description: '"prod", "preprod", "dev" are the only valid values'
        required: true
      packageId:
        description: "Get the package ID from Releases"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Input Values
      - name: "Input Values"
        run: |
          echo "Org: ${{ github.event.inputs.org }}"
          echo "Package ID: ${{ github.event.inputs.packageId }}"
          echo "Initiator: ${{ github.actor }}"

      # Set auth URL
      - name: "Set auth URL"
        id: auth-url
        run: |
          if [ ${{ github.event.inputs.org }} == "prod" ]
          then
            echo "::set-output name=target::$(echo ${{ secrets.PROD_SFDX_URL }})"
          elif [ ${{ github.event.inputs.org }} == "preprod" ]
          then
            echo "::set-output name=target::$(echo ${{ secrets.PREPROD_SFDX_URL }})"
          elif [ ${{ github.event.inputs.org }} == "dev" ]
          then
            echo "::set-output name=target::$(echo ${{ secrets.DEV_SFDX_URL }})"
          fi

      # Authorize SFDX
      - name: Authorize SFDX
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ steps.auth-url.outputs.target }}

      # Install package in target org
      - name: "Install package in target org"
        run: "sfdx force:package:install --package ${{ github.event.inputs.packageId }} -k ${{ secrets.PACKAGE_KEY }} -w 10 -b 10 -r"
